"""add_user_and_order_fields

Revision ID: 36f02dbfb6c0
Revises: ca93f763bc00
Create Date: 2025-11-01 22:43:58.262757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f02dbfb6c0'
down_revision = 'ca93f763bc00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем product_name как nullable сначала
    op.add_column('orders', sa.Column('product_name', sa.String(), nullable=True))
    # Заполняем существующие записи значением из title
    op.execute("UPDATE orders SET product_name = title WHERE product_name IS NULL")
    # Теперь делаем колонку NOT NULL
    op.alter_column('orders', 'product_name', nullable=False)
    
    op.add_column('orders', sa.Column('delivery_volume', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('purchase_budget', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('product_description', sa.Text(), nullable=True))
    op.alter_column('orders', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('organization_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('inn', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'inn')
    op.drop_column('users', 'organization_name')
    op.alter_column('orders', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'product_description')
    op.drop_column('orders', 'purchase_budget')
    op.drop_column('orders', 'delivery_volume')
    op.drop_column('orders', 'product_name')
    # ### end Alembic commands ###

