"""add_email_notifications_field

Revision ID: d55ee86d41d3
Revises: cbbee1c6aa81
Create Date: 2025-11-05 16:55:01.051306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55ee86d41d3'
down_revision = 'cbbee1c6aa81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True))
    # Устанавливаем значение по умолчанию для всех существующих записей
    op.execute("UPDATE users SET email_notifications = TRUE WHERE email_notifications IS NULL")
    # Теперь делаем колонку NOT NULL
    op.alter_column('users', 'email_notifications', nullable=False, server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###

