"""add_supplier_user_id

Revision ID: e11487a683cb
Revises: 36f02dbfb6c0
Create Date: 2025-11-01 23:07:39.527112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11487a683cb'
down_revision = '36f02dbfb6c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'suppliers', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'user_id')
    # ### end Alembic commands ###

